site_name: Subtitle Anything!
site_url: https://www.subtitle-anything.com
site_author: ae9is
site_description: >-
  Add AI generated subtitles to any video playing in your browser!
repo_name: ae9is/subtitle-anything
repo_url: https://github.com/ae9is/subtitle-anything
edit_uri: edit/main/docs/src/
docs_dir: src
plugins:
  - search
markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ae9is/subtitle-anything
#  analytics:
#    provider: google
#    property: !ENV GOOGLE_ANALYTICS_KEY
#  consent:
#    title: Would you like a free cookie? 🍪
#    description: It's just to see how this docs site is used and potentially improve it.
#    actions:
#      - manage
#      - reject
#      - accept
#copyright: <a href="#__consent">Change cookie settings</a>
extra_css:
  - assets/extra.css
theme:
  name: material
  logo: assets/icon.svg
  favicon: assets/icon-128.png
  palette:
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: custom
      accent: custom
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: white
      accent: white
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - navigation.path
    - navigation.top
#    - navigation.sections
#    - navigation.tabs
    - search.highlight
    - search.share
    - toc.follow
  icon:
    edit: material/pencil 
    view: material/eye
nav:
  - About: index.md
  - install.md
  - usage.md
#  - changelog.md
#  - credits.md
